version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Configure Git
          command: |
            git config --global user.name 'CircleCI'
            git config --global user.email 's+circleci@sugarshin.net'
      - restore_cache:
          name: Restoring Cache - dependencies
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Test
          command: npm test
      - save_cache:
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - deploy:
          command: |
            npm run deployment:pop
            ./node_modules/.bin/now --public -e NODE_ENV=production -e SENTRY_DSN=$SENTRY_DSN -n moci --token=$NOW_TOKEN
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./node_modules/.bin/now scale moci.now.sh 1 --token=$NOW_TOKEN
              npm run alias -- --token=$NOW_TOKEN &>/dev/null
              ./node_modules/.bin/now scale moci.now.sh 1 2 --token=$NOW_TOKEN
              npm run deployment:delete
              node scripts/slack-notify
            fi
